import crypto from 'crypto';import {NextRequest,NextResponse} from 'next/server';import {query} from '@/lib/db';import {refundWhopPayment,cancelWhopMembership} from '@/lib/whop';
function equal(a:string,b:string){if(!a||!b||a.length!==b.length)return false;try{return crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b));}catch{return false;}}
export async function POST(request:NextRequest){const body=await request.json();const apiKey=String(body.apiKey||body.api_key||request.headers.get('x-api-key')||'');let locationId=String(body.locationId||request.nextUrl.searchParams.get('locationId')||'');if(!locationId&&apiKey){const owners=await query<any[]>('SELECT location_id FROM whop_ghl_installations WHERE provider_api_key=? LIMIT 1',[apiKey]);locationId=owners[0]?.location_id||'';}const installs=await query<any[]>('SELECT provider_api_key,whop_api_key FROM whop_ghl_installations WHERE location_id=? LIMIT 1',[locationId]);if(!equal(String(installs[0]?.provider_api_key||''),apiKey))return NextResponse.json({error:'unauthorized'},{status:401});
 const chargeId=String(body.chargeId||'');const txn=String(body.transactionId||body.ghlTransactionId||'');const rows=await query<any[]>(`SELECT * FROM payments WHERE location_id=? AND provider='whop' AND (pf_payment_id=? OR pf_token=? OR custom_str3=?) ORDER BY id DESC LIMIT 1`,[locationId,chargeId,chargeId,txn]);const payment=rows[0];
 if(body.type==='verify'){if(!payment)return NextResponse.json({success:false,message:'Payment not found'});const success=payment.status==='complete';const failed=['failed','cancelled','refunded'].includes(payment.status);const id=payment.pf_payment_id||payment.pf_token||chargeId;return NextResponse.json({success,failed,message:success?'Payment verified':failed?'Payment failed':'Payment pending',chargeSnapshot:{id,chargeId:id,status:success?'succeeded':failed?'failed':'pending',amount:Number(payment.amount||0),chargedAt:Math.floor(new Date(payment.updated_at||payment.created_at||Date.now()).getTime()/1000)}});}
 if(body.type==='refund'){if(!payment)return NextResponse.json({success:false,message:'Payment not found'},{status:404});const amount=Number(body.amount||payment.amount);const result=await refundWhopPayment({apiKey:String(installs[0].whop_api_key||''),paymentId:String(payment.pf_payment_id||''),partialAmount:amount});if(!result.ok)return NextResponse.json({success:false,failed:true,message:result.error},{status:400});await query(`INSERT INTO payment_refunds(payment_id,location_id,provider,provider_refund_id,amount,currency,status,raw_response) VALUES(?,?,'whop',?,?,'USD','succeeded',?)`,[payment.id,locationId,String(result.data?.id||`${payment.pf_payment_id}:refund:${Date.now()}`),amount,JSON.stringify(result.data||{})]);if(amount>=Number(payment.amount))await query(`UPDATE payments SET status='refunded' WHERE id=?`,[payment.id]);return NextResponse.json({success:true,message:'Refund successful'});}
 if(body.type==='cancel_subscription'){if(!payment?.whop_membership_id)return NextResponse.json({success:false,message:'Subscription not found'},{status:404});const result=await cancelWhopMembership({apiKey:String(installs[0].whop_api_key||''),membershipId:String(payment.whop_membership_id),atPeriodEnd:false});if(!result.ok)return NextResponse.json({success:false,message:result.error},{status:400});await query(`UPDATE payments SET status='cancelled' WHERE id=?`,[payment.id]);return NextResponse.json({success:true,status:'canceled'});}
 return NextResponse.json({error:'Unsupported Whop query type'},{status:400});}
export async function GET(){return NextResponse.json({status:'ok',provider:'10x Whop App'});}
