import {NextRequest,NextResponse} from 'next/server';
import {query} from '@/lib/db';import {verifyWhopSignature} from '@/lib/whop';import {savePaymentInstrument} from '@/lib/payment-instruments';import {sendWhopGhlNotification} from '@/lib/whop-ghl-notify';
function changed(result:unknown){return Number((result as{affectedRows?:number}|null)?.affectedRows||0)===1;}
export async function POST(request:NextRequest){const rawBody=await request.text();let data:any=null;try{data=rawBody?JSON.parse(rawBody):null;}catch{}if(!data)return new NextResponse('Invalid payload',{status:400});const meta=(data?.data?.metadata||{}) as Record<string,string>;const locationId=String(meta.location_id||'');const basketId=String(meta.basketId||meta.setup_id||'');if(meta.app!=='whop'||!locationId||!basketId)return new NextResponse('Missing standalone Whop metadata',{status:400});
 const installs=await query<any[]>('SELECT whop_webhook_secret FROM whop_ghl_installations WHERE location_id=? LIMIT 1',[locationId]);const secret=String(installs[0]?.whop_webhook_secret||'');if(!verifyWhopSignature({msgId:request.headers.get('webhook-id'),timestamp:request.headers.get('webhook-timestamp'),signature:request.headers.get('webhook-signature'),rawBody,secret}))return new NextResponse('Invalid signature',{status:401});
 const payments=await query<any[]>(`SELECT * FROM payments WHERE pf_token=? AND location_id=? AND provider='whop' ORDER BY id DESC LIMIT 1`,[basketId,locationId]);if(!payments.length)return new NextResponse('Payment not found',{status:404});const payment=payments[0];const type=String(data?.type||data?.action||'');
 if(type==='payment.failed'||type==='payment_failed'){await query(`UPDATE payments SET status='failed',raw_itn=?,updated_at=NOW() WHERE id=? AND status='pending'`,[JSON.stringify(data),payment.id]);return new NextResponse('OK');}
 if(meta.kind==='ghl_payment_method_setup'&&(type==='setup_intent.succeeded'||type==='setup_intent_succeeded')){const setup=data?.data||{};const method=setup.payment_method||{};const methodId=String(method.id||setup.payment_method_id||'');if(!methodId)return new NextResponse('Missing payment method',{status:400});const card=method.card||{};await savePaymentInstrument(locationId,{contactId:String(meta.contact_id||''),provider:'whop',providerCustomerId:setup.member?.id?String(setup.member.id):null,providerPaymentMethodId:methodId,instrumentToken:methodId,instrumentAlias:card.brand||'Whop card',cardLastFour:card.last4||card.last_four||null,expiryDate:card.exp_month&&card.exp_year?`${card.exp_month}/${String(card.exp_year).slice(-2)}`:null,isDefault:true});await query(`UPDATE payments SET status='complete',pf_payment_id=?,raw_itn=?,updated_at=NOW() WHERE id=? AND status='pending'`,[String(setup.id||methodId),JSON.stringify(data),payment.id]);return new NextResponse('OK');}
 const success=type==='payment.succeeded'||type==='payment_succeeded'||type==='membership.renewed'||type==='membership_renewed';if(!success)return new NextResponse('Ignored');const paymentId=String(data?.data?.id||basketId);const membershipId=data?.data?.membership?.id?String(data.data.membership.id):null;const transition=await query<any>(`UPDATE payments SET pf_payment_id=?,status='complete',whop_membership_id=COALESCE(?,whop_membership_id),raw_itn=?,updated_at=NOW() WHERE id=? AND status='pending'`,[paymentId,membershipId,JSON.stringify(data),payment.id]);const complete=changed(transition)||payment.status==='complete';
 let metadata:any=null;try{metadata=payment.item_description?JSON.parse(payment.item_description):null;}catch{}if(complete&&payment.custom_str3){const claim=await query<any>(`UPDATE payments SET synced_ghl=-1 WHERE id=? AND status='complete' AND COALESCE(synced_ghl,0)=0`,[payment.id]);if(changed(claim)){try{const result=await sendWhopGhlNotification({locationId,ghlTransactionId:payment.custom_str3,chargeId:paymentId,amount:Number(payment.amount),contactId:metadata?.contactId||payment.contact_id||null,invoiceId:metadata?.invoiceId||null,orderId:metadata?.orderId||null,subscriptionId:metadata?.subscriptionId||null,eventType:payment.payment_type==='subscription'?'subscription.charged':'payment.captured'});if(result.ok)await query('UPDATE payments SET synced_ghl=1 WHERE id=? AND synced_ghl=-1',[payment.id]);else if(result.status===429||result.status>=500)await query('UPDATE payments SET synced_ghl=0 WHERE id=? AND synced_ghl=-1',[payment.id]);}catch(error){console.error('[Whop App] notification failed',error);await query('UPDATE payments SET synced_ghl=0 WHERE id=? AND synced_ghl=-1',[payment.id]);}}}return new NextResponse('OK');}
export async function GET(){return NextResponse.json({status:'ok',app:'whop',endpoint:'payment webhook'});}
